package com.kamanon.domain.model.mybatis.entity;

import java.time.LocalDate;

public class TFollow {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_follow.user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_follow.follow_user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private Long followUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_follow.created
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private LocalDate created;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_follow.user_id
	 * @return  the value of t_follow.user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_follow.user_id
	 * @param userId  the value for t_follow.user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_follow.follow_user_id
	 * @return  the value of t_follow.follow_user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public Long getFollowUserId() {
		return followUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_follow.follow_user_id
	 * @param followUserId  the value for t_follow.follow_user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setFollowUserId(Long followUserId) {
		this.followUserId = followUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_follow.created
	 * @return  the value of t_follow.created
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public LocalDate getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_follow.created
	 * @param created  the value for t_follow.created
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setCreated(LocalDate created) {
		this.created = created;
	}
}