package com.kamanon.domain.model.mybatis.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class TTweetAction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_tweet_action.user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_tweet_action.tweet_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private Long tweetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_tweet_action.retweet_flg
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private String retweetFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_tweet_action.like_flg
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private String likeFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_tweet_action.created
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private LocalDate created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_tweet_action.updated
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	private LocalDateTime updated;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_tweet_action.user_id
	 * @return  the value of t_tweet_action.user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_tweet_action.user_id
	 * @param userId  the value for t_tweet_action.user_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_tweet_action.tweet_id
	 * @return  the value of t_tweet_action.tweet_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public Long getTweetId() {
		return tweetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_tweet_action.tweet_id
	 * @param tweetId  the value for t_tweet_action.tweet_id
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setTweetId(Long tweetId) {
		this.tweetId = tweetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_tweet_action.retweet_flg
	 * @return  the value of t_tweet_action.retweet_flg
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public String getRetweetFlg() {
		return retweetFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_tweet_action.retweet_flg
	 * @param retweetFlg  the value for t_tweet_action.retweet_flg
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setRetweetFlg(String retweetFlg) {
		this.retweetFlg = retweetFlg == null ? null : retweetFlg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_tweet_action.like_flg
	 * @return  the value of t_tweet_action.like_flg
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public String getLikeFlg() {
		return likeFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_tweet_action.like_flg
	 * @param likeFlg  the value for t_tweet_action.like_flg
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setLikeFlg(String likeFlg) {
		this.likeFlg = likeFlg == null ? null : likeFlg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_tweet_action.created
	 * @return  the value of t_tweet_action.created
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public LocalDate getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_tweet_action.created
	 * @param created  the value for t_tweet_action.created
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setCreated(LocalDate created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_tweet_action.updated
	 * @return  the value of t_tweet_action.updated
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public LocalDateTime getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_tweet_action.updated
	 * @param updated  the value for t_tweet_action.updated
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	public void setUpdated(LocalDateTime updated) {
		this.updated = updated;
	}
}