package com.kamanon.domain.model.mybatis.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class TTweetAction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tweet_action.user_id
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tweet_action.tweet_id
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    private Long tweetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tweet_action.tweet
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    private String tweet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tweet_action.created
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    private LocalDate created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tweet_action.updated
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    private LocalDateTime updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tweet_action.user_id
     *
     * @return the value of t_tweet_action.user_id
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tweet_action.user_id
     *
     * @param userId the value for t_tweet_action.user_id
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tweet_action.tweet_id
     *
     * @return the value of t_tweet_action.tweet_id
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public Long getTweetId() {
        return tweetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tweet_action.tweet_id
     *
     * @param tweetId the value for t_tweet_action.tweet_id
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public void setTweetId(Long tweetId) {
        this.tweetId = tweetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tweet_action.tweet
     *
     * @return the value of t_tweet_action.tweet
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public String getTweet() {
        return tweet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tweet_action.tweet
     *
     * @param tweet the value for t_tweet_action.tweet
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public void setTweet(String tweet) {
        this.tweet = tweet == null ? null : tweet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tweet_action.created
     *
     * @return the value of t_tweet_action.created
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public LocalDate getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tweet_action.created
     *
     * @param created the value for t_tweet_action.created
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public void setCreated(LocalDate created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tweet_action.updated
     *
     * @return the value of t_tweet_action.updated
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public LocalDateTime getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tweet_action.updated
     *
     * @param updated the value for t_tweet_action.updated
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    public void setUpdated(LocalDateTime updated) {
        this.updated = updated;
    }
}