package com.kamanon.domain.model.mybatis.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class TUsr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.user_id
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.user_name
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.password
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.handle_name
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private String handleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.email_addr
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private String emailAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.sex
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.birthday
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private LocalDate birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.created
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private LocalDateTime created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_usr.updated
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	private LocalDateTime updated;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.user_id
	 * @return  the value of t_usr.user_id
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.user_id
	 * @param userId  the value for t_usr.user_id
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.user_name
	 * @return  the value of t_usr.user_name
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.user_name
	 * @param userName  the value for t_usr.user_name
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.password
	 * @return  the value of t_usr.password
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.password
	 * @param password  the value for t_usr.password
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.handle_name
	 * @return  the value of t_usr.handle_name
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public String getHandleName() {
		return handleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.handle_name
	 * @param handleName  the value for t_usr.handle_name
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setHandleName(String handleName) {
		this.handleName = handleName == null ? null : handleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.email_addr
	 * @return  the value of t_usr.email_addr
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public String getEmailAddr() {
		return emailAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.email_addr
	 * @param emailAddr  the value for t_usr.email_addr
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr == null ? null : emailAddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.sex
	 * @return  the value of t_usr.sex
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.sex
	 * @param sex  the value for t_usr.sex
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.birthday
	 * @return  the value of t_usr.birthday
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public LocalDate getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.birthday
	 * @param birthday  the value for t_usr.birthday
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setBirthday(LocalDate birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.created
	 * @return  the value of t_usr.created
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public LocalDateTime getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.created
	 * @param created  the value for t_usr.created
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setCreated(LocalDateTime created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_usr.updated
	 * @return  the value of t_usr.updated
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public LocalDateTime getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_usr.updated
	 * @param updated  the value for t_usr.updated
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	public void setUpdated(LocalDateTime updated) {
		this.updated = updated;
	}
}