package com.kamanon.domain.model.mybatis.entity;

import java.util.Date;

public class Tweet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet.user_id
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet.tweet
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    private String tweet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet.created
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet.user_id
     *
     * @return the value of tweet.user_id
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet.user_id
     *
     * @param userId the value for tweet.user_id
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet.tweet
     *
     * @return the value of tweet.tweet
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    public String getTweet() {
        return tweet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet.tweet
     *
     * @param tweet the value for tweet.tweet
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    public void setTweet(String tweet) {
        this.tweet = tweet == null ? null : tweet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet.created
     *
     * @return the value of tweet.created
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet.created
     *
     * @param created the value for tweet.created
     *
     * @mbg.generated Wed Jun 12 10:04:01 JST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}