package com.kamanon.domain.model.mybatis.mapper;

import com.kamanon.domain.model.mybatis.entity.TFollow;
import com.kamanon.domain.model.mybatis.entity.TFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFollowMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_follow
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	long countByExample(TFollowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_follow
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int deleteByExample(TFollowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_follow
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int insert(TFollow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_follow
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int insertSelective(TFollow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_follow
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	List<TFollow> selectByExample(TFollowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_follow
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int updateByExampleSelective(@Param("record") TFollow record, @Param("example") TFollowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_follow
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int updateByExample(@Param("record") TFollow record, @Param("example") TFollowExample example);
}