package com.kamanon.domain.model.mybatis.mapper;

import com.kamanon.domain.model.mybatis.entity.TTweetAction;
import com.kamanon.domain.model.mybatis.entity.TTweetActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTweetActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tweet_action
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    long countByExample(TTweetActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tweet_action
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    int deleteByExample(TTweetActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tweet_action
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    int insert(TTweetAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tweet_action
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    int insertSelective(TTweetAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tweet_action
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    List<TTweetAction> selectByExample(TTweetActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tweet_action
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    int updateByExampleSelective(@Param("record") TTweetAction record, @Param("example") TTweetActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tweet_action
     *
     * @mbg.generated Fri Jul 05 18:35:24 JST 2019
     */
    int updateByExample(@Param("record") TTweetAction record, @Param("example") TTweetActionExample example);
}