package com.kamanon.domain.model.mybatis.mapper;

import com.kamanon.domain.model.mybatis.entity.TTweet;
import com.kamanon.domain.model.mybatis.entity.TTweetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTweetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	long countByExample(TTweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	int deleteByExample(TTweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	int deleteByPrimaryKey(Long tweetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	int insert(TTweet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	int insertSelective(TTweet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	List<TTweet> selectByExample(TTweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	TTweet selectByPrimaryKey(Long tweetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	int updateByExampleSelective(@Param("record") TTweet record, @Param("example") TTweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	int updateByExample(@Param("record") TTweet record, @Param("example") TTweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	int updateByPrimaryKeySelective(TTweet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tweet
	 * @mbg.generated  Fri Jul 05 18:35:24 JST 2019
	 */
	int updateByPrimaryKey(TTweet record);
}