package com.kamanon.domain.model.mybatis.mapper;

import com.kamanon.domain.model.mybatis.entity.TUsr;
import com.kamanon.domain.model.mybatis.entity.TUsrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUsrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	long countByExample(TUsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int deleteByExample(TUsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int insert(TUsr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int insertSelective(TUsr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	List<TUsr> selectByExample(TUsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	TUsr selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int updateByExampleSelective(@Param("record") TUsr record, @Param("example") TUsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int updateByExample(@Param("record") TUsr record, @Param("example") TUsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int updateByPrimaryKeySelective(TUsr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_usr
	 * @mbg.generated  Sun Jul 07 18:22:44 JST 2019
	 */
	int updateByPrimaryKey(TUsr record);
}