package com.kamanon.domain.model.mybatis.mapper;

import com.kamanon.domain.model.mybatis.entity.Tweet;
import com.kamanon.domain.model.mybatis.entity.TweetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TweetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tweet
	 * @mbg.generated  Fri Jun 14 11:31:13 JST 2019
	 */
	long countByExample(TweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tweet
	 * @mbg.generated  Fri Jun 14 11:31:13 JST 2019
	 */
	int deleteByExample(TweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tweet
	 * @mbg.generated  Fri Jun 14 11:31:13 JST 2019
	 */
	int insert(Tweet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tweet
	 * @mbg.generated  Fri Jun 14 11:31:13 JST 2019
	 */
	int insertSelective(Tweet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tweet
	 * @mbg.generated  Fri Jun 14 11:31:13 JST 2019
	 */
	List<Tweet> selectByExample(TweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tweet
	 * @mbg.generated  Fri Jun 14 11:31:13 JST 2019
	 */
	int updateByExampleSelective(@Param("record") Tweet record, @Param("example") TweetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tweet
	 * @mbg.generated  Fri Jun 14 11:31:13 JST 2019
	 */
	int updateByExample(@Param("record") Tweet record, @Param("example") TweetExample example);
}